version: "3.7"
services:
  minidlna:
    image: johnelse/docker-minidlna
    network_mode: host
    volumes:
      - '/geneva/:/geneva:ro'
    environment:
      - MINIDLNA_FRIENDLY_NAME=${HOSTNAME}
      - 'MINIDLNA_MEDIA_DIR=/geneva/'
  samba:
    image: pwntr/samba-alpine
    restart: always
    network_mode: host
    volumes:
      - '/geneva/:/shared'
      - '${PWD}/smb.conf:/config/smb.conf'
  
