version: "3.7"
services:
  samba:
    image: pwntr/samba-alpine
    restart: always
    network_mode: host
    volumes:
      - '/geneva/:/shared/geneva'
      - '/tank/:/shared/tank'
      - '${PWD}/smb.conf:/config/smb.conf'
  
