version: "3.7"
services:
  samba:
    image: pwntr/samba-alpine
    restart: always
    network_mode: host
    volumes:
      - '/geneva/:/shared/geneva'
      - '/geneva-usb/:/shared/geneva-usb'
      - '${PWD}/smb.conf:/config/smb.conf'
  
